services:
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    command: npm start 
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend:/src
